version: '3.7'
services:
  neo4j:
    image: neo4j:3.5
    restart: unless-stopped
    ports:
      - ${NEO4J_ADMIN_PORT}:${NEO4J_ADMIN_PORT}
      - ${NEO4J_PORT}:${NEO4J_PORT}
    volumes:
      - ./graph-db/conf:/conf
      - ./graph-db/data:/data
      - ./graph-db/import:/import
      - ./graph-db/logs:/logs
      - ./graph-db/plugins:/plugins
    env_file:
      - ./.env

  postgres:
    image: postgres:10.4
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - ./.env
    volumes:
      - ./storage/postgresql/data:/var/lib/postgresql/data
    logging:
      driver: none
