swagger: '2.0'

info:
  title: People Graph HTTP Server API
  description: Endpoints for getting data by browser client
  version: 0.0.0

consumes:
  - application/json

produces:
  - application/json

paths:
  /healthcheck:
    get:
      tags:
        - system
      summary: Returns 200 OK response if server is working
      responses:
        200:
          description: data about health of the system
          schema:
            type: object
            properties:
              metadata:
                type: object
                properties:
                  timestamp:
                    type: string
                    example: '1589137051680'
              data:
                type: object
                properties:
                  version:
                    type: string
                    example: '0.0.0'
                  message:
                    type: string
                    example: 'ok'
