name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  vulncheck:
    name: Vulnerability check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Audit dependencies
        run: yarn audit
        continue-on-error: true
